name: rarepdftool-api
region: nyc
services:
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /pdf-tools-phase1/server_py
    
    # Build configuration
    build_command: pip install -r requirements.txt
    
    # Run configuration  
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    
    # Environment
    envs:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8080"
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month
    
    # HTTP configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
